# -*- coding: utf-8 -*-
"""python_operators_practice (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hnT18J0PDLnE0lfam7j35fl7QlF2G7-d

# Python Operators Practice Notebook

Each question is followed by its solution in the next code cell.
Difficulty level: Easy to Medium.

## Arithmetic Operators

Q1. Add two numbers a = 10 and b = 5.
"""

# write your answer here

a = 10
b = 5
print(a+b)

"""Q2. Find the remainder when 17 is divided by 4."""

# write your answer here
a = 17
b = 4
print(a%b)

"""Q3. Calculate 3 raised to the power 4."""

# write your answer here
print(3**4)

"""## Assignment Operators

Q4. Assign 10 to x and add 5 to it using assignment operator.
"""

# write your answer here
x = 10
x += 5
print(x)

"""Q5. Assign 20 to y and multiply it by 2 using assignment operator."""

# write your answer here
y = 20
y *= 2
print(y)

"""Q6. Assign 15 to z and subtract 7 using assignment operator."""

# write your answer here
z = int(input("Enter a number: "))
z -= 7
print(z)

"""## Comparison Operators

Q7. Check if 10 is greater than 5.
"""

# write your answer here
print(10>5)

"""Q8. Check if 7 is equal to 9."""

# write your answer here
print(7==9)

"""Q9. Check if 8 is not equal to 3."""

# write your answer here
print(8!=3)

"""## Logical Operators

Q10. Check if 5 > 2 and 10 > 3.
"""

# write your answer here
print(5>2 and 10>3)

"""Q11. Check if 5 > 10 or 3 < 7."""

# write your answer here
print(5>10 or 3<7)

"""Q12. Use not operator on condition 10 > 5."""

# write your answer here
print(not 10>5)

"""## Identity Operators

Q16. Check if a and b refer to the same object.
Let a = 10, b = 10.
"""

# write your answer here
a = 10
b = 10
print(a is b)

"""Q18. Compare identity of two variables c and d where c = d = 5."""

# write your answer here
c = 5
d = 5
x = c is d
print(x)

"""## Membership Operators

Q19. Check if 3 is present in the list [1,2,3,4].
"""

# write your answer here
a = [1,2,3,4]
print(3 in a)

"""Q20. Check if 'a' is not present in the string 'python'."""

# write your answer here
a = "python"
print("a" not in a)

"""Q21. Check if 10 is in the tuple (5, 10, 15)."""

# write your answer here
a = (5,10,15)
print(10 in a)