# -*- coding: utf-8 -*-
"""python_arithmetic_operators_practice.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kZic7wUOHqoiENFyMduotTK6yqPXrut8

# Python Arithmetic Operators Practice Notebook

# Q1  Addition

Write an expression that adds `8` and `12` and prints the result.
"""

# Answer here
print(8+12)



"""# Q2  Subtraction

Write an expression that subtracts `7` from `20` and prints the result.
"""

# Answer here
print(7-20)

"""# Q3  Multiplication

Write an expression that multiplies `6` by `9` and prints the result.
"""

# Answer here
print(6*9)

"""# Q4  Division

Write an expression that divides `45` by `9` and prints the result (normal division).
"""

# Answer here
print(45/9)

"""# Q5  Floor Division

Write an expression that floor-divides `45` by `9` and prints the result.

Then floor-divide `50` by `6` and print the result to see how floor division works.
"""

# Answer here
print(45//9)
print(50//6)

"""# Q6  Modulus

Write an expression that computes the remainder when `29` is divided by `5` and prints it.
"""

# Answer here
print(29%5)

"""# Q7  Power

Compute `3` raised to the power `4` and print the result using the `**` operator.
"""

# Answer here
num=3
power=4
print(3**4)

"""# Q8  Unary plus and minus

Assign a positive number to a variable `x` and print `+x` and `-x`. Observe the outputs.
"""

# Answer here
x=10

print(+x)
print(-x)

"""# Q9  Combined expression and operator precedence

Without using parentheses, write an expression that computes `5 + 3 * 2` and prints the result. Then add parentheses to change the order so that addition happens first: `(5 + 3) * 2`.
"""

# Answer here
x= 5+3*2
y=(5+3)*2

print(x)
print(y)

"""# Q10  Using variables

Assign two variables `a = 15` and `b = 4`. Compute and print **all** arithmetic operations between them: `+`, `-`, `*`, `/`, `//`, `%`, `**`.
"""

# Answer here
a=15
b=4

print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a//b)
print(a%b)
print(a**b)

"""# Q11 - Compound assignment

Start with `n = 10`. Use compound assignment operators to:
- add 5 (`n += 5`), print
- multiply by 2 (`n *= 2`), print
- subtract 4 (`n -= 4`), print
(Place each statement so students can see the updated `n` after each operation.)
"""

# Answer here
n=10
print(n)
n+=5
print(n)
n*=2
print(n)
n-=4
print(n)

"""# Q12  Swapping values (without a third variable)

Given `x = 3` and `y = 7`, swap their values using Python tuple assignment and print `x` and `y` after swapping.
"""

# Answer here
x = 3
y = 7

"""# Q13 - Input: Sum of two numbers

Ask the user to input two numbers (integers). Add them and print `Sum: <result>`.
"""

# Answer here
# Hint: use input(), then convert to int() or float() as needed.

"""# Q14 - Input: Average of three numbers

Ask the user to input three numbers (floats allowed). Compute their average and print `Average: <result>`.
"""

# Answer here
# Hint: use input(), then convert to int() or float() as needed.

"""# Q15 - Input: Circle calculations

Ask the user to input the radius of a circle (float). Compute and print:
- Circumference = `2 * 3.14159 * radius`
- Area = `3.14159 * radius ** 2`
"""

# Answer here
# Hint: use input(), then convert to int() or float() as needed.

"""# Q16 - Input: Convert total seconds to hours, minutes, seconds

Ask the user to input a total number of seconds (integer). Convert it to hours, minutes, and seconds and print as `H:M:S`.
"""

# Answer here
# Hint: use input(), then convert to int() or float() as needed.

"""# Q17 - Input: Simple interest calculation

Ask user for `principal`, `rate` (annual percent), and `time` (years). Compute simple interest as `(principal * rate * time) / 100` and print `Interest: <result>`.
"""

# Answer here